title:               Celeste
url:                 https://ekhiyami.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            20
paginate_path:       /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              EB Khiyami
  url:               ekhiyami.github.io
  email:             

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist